[phases.install]
cmds = [
  "COMPOSER_PROCESS_TIMEOUT=600 composer install --no-dev --optimize-autoloader --prefer-dist",
  "npm install"
]

[phases.build]
cmds = [
  "npm run prod"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8000"
